services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis-container
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgis_data:

networks:
  postgres_network:
    driver: bridge