services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis-container
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - postgres_network
  mongo:
    image: mongo
    container_name: mongodb
    networks:
      - mongo_network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart : always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
        - mongo_network

volumes:
  postgis_data:
  mongo_data:

networks:
  postgres_network:
    driver: bridge
  mongo_network:
    driver: bridge