services:
  postgres_db:
    image: postgres:latest
    env_file:
      - .env
    restart: unless-stopped
    #se usa bridge asi que es necesario!!
    ports:
      - "5432:5432"
    # se puede definir un volumen pero como es solo prueba, no es necesario
    networks:
      - postgres_network
networks:
  postgres_network:
    driver: bridge