services:
  postgres_db:
    image: postgres:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "5433:5433"
    networks:
      - postgres_network
networks:
  postgres_network:
    driver: bridge